/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.payment;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PaymentEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2604290590178931724L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PaymentEvent\",\"namespace\":\"com.emi.events.payment\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"paymentId\",\"type\":\"string\"},{\"name\":\"userKeycloakId\",\"type\":\"string\"},{\"name\":\"currency\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"long\",\"doc\":\"Amount in smallest currency unit\"},{\"name\":\"paymentType\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentType\",\"symbols\":[\"DEPOSIT\",\"TRANSFER\",\"WITHDRAW\"]}},{\"name\":\"paymentStatus\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentStatus\",\"symbols\":[\"INITIATED\",\"SUCCESS\",\"FAILED\",\"REFUNDED\"]}},{\"name\":\"paymentMethod\",\"type\":{\"type\":\"enum\",\"name\":\"PaymentMethodType\",\"symbols\":[\"CARD\",\"UPI\",\"NET_BANKING\",\"WALLET\"]}},{\"name\":\"createdAt\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PaymentEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PaymentEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PaymentEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PaymentEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PaymentEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PaymentEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PaymentEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PaymentEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PaymentEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventId;
  private java.lang.CharSequence paymentId;
  private java.lang.CharSequence userKeycloakId;
  private java.lang.CharSequence currency;
  /** Amount in smallest currency unit */
  private long amount;
  private com.emi.events.payment.PaymentType paymentType;
  private com.emi.events.payment.PaymentStatus paymentStatus;
  private com.emi.events.payment.PaymentMethodType paymentMethod;
  private long createdAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PaymentEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param paymentId The new value for paymentId
   * @param userKeycloakId The new value for userKeycloakId
   * @param currency The new value for currency
   * @param amount Amount in smallest currency unit
   * @param paymentType The new value for paymentType
   * @param paymentStatus The new value for paymentStatus
   * @param paymentMethod The new value for paymentMethod
   * @param createdAt The new value for createdAt
   */
  public PaymentEvent(java.lang.CharSequence eventId, java.lang.CharSequence paymentId, java.lang.CharSequence userKeycloakId, java.lang.CharSequence currency, java.lang.Long amount, com.emi.events.payment.PaymentType paymentType, com.emi.events.payment.PaymentStatus paymentStatus, com.emi.events.payment.PaymentMethodType paymentMethod, java.lang.Long createdAt) {
    this.eventId = eventId;
    this.paymentId = paymentId;
    this.userKeycloakId = userKeycloakId;
    this.currency = currency;
    this.amount = amount;
    this.paymentType = paymentType;
    this.paymentStatus = paymentStatus;
    this.paymentMethod = paymentMethod;
    this.createdAt = createdAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return paymentId;
    case 2: return userKeycloakId;
    case 3: return currency;
    case 4: return amount;
    case 5: return paymentType;
    case 6: return paymentStatus;
    case 7: return paymentMethod;
    case 8: return createdAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: paymentId = (java.lang.CharSequence)value$; break;
    case 2: userKeycloakId = (java.lang.CharSequence)value$; break;
    case 3: currency = (java.lang.CharSequence)value$; break;
    case 4: amount = (java.lang.Long)value$; break;
    case 5: paymentType = (com.emi.events.payment.PaymentType)value$; break;
    case 6: paymentStatus = (com.emi.events.payment.PaymentStatus)value$; break;
    case 7: paymentMethod = (com.emi.events.payment.PaymentMethodType)value$; break;
    case 8: createdAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'paymentId' field.
   * @return The value of the 'paymentId' field.
   */
  public java.lang.CharSequence getPaymentId() {
    return paymentId;
  }


  /**
   * Sets the value of the 'paymentId' field.
   * @param value the value to set.
   */
  public void setPaymentId(java.lang.CharSequence value) {
    this.paymentId = value;
  }

  /**
   * Gets the value of the 'userKeycloakId' field.
   * @return The value of the 'userKeycloakId' field.
   */
  public java.lang.CharSequence getUserKeycloakId() {
    return userKeycloakId;
  }


  /**
   * Sets the value of the 'userKeycloakId' field.
   * @param value the value to set.
   */
  public void setUserKeycloakId(java.lang.CharSequence value) {
    this.userKeycloakId = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return Amount in smallest currency unit
   */
  public long getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * Amount in smallest currency unit
   * @param value the value to set.
   */
  public void setAmount(long value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'paymentType' field.
   * @return The value of the 'paymentType' field.
   */
  public com.emi.events.payment.PaymentType getPaymentType() {
    return paymentType;
  }


  /**
   * Sets the value of the 'paymentType' field.
   * @param value the value to set.
   */
  public void setPaymentType(com.emi.events.payment.PaymentType value) {
    this.paymentType = value;
  }

  /**
   * Gets the value of the 'paymentStatus' field.
   * @return The value of the 'paymentStatus' field.
   */
  public com.emi.events.payment.PaymentStatus getPaymentStatus() {
    return paymentStatus;
  }


  /**
   * Sets the value of the 'paymentStatus' field.
   * @param value the value to set.
   */
  public void setPaymentStatus(com.emi.events.payment.PaymentStatus value) {
    this.paymentStatus = value;
  }

  /**
   * Gets the value of the 'paymentMethod' field.
   * @return The value of the 'paymentMethod' field.
   */
  public com.emi.events.payment.PaymentMethodType getPaymentMethod() {
    return paymentMethod;
  }


  /**
   * Sets the value of the 'paymentMethod' field.
   * @param value the value to set.
   */
  public void setPaymentMethod(com.emi.events.payment.PaymentMethodType value) {
    this.paymentMethod = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public long getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(long value) {
    this.createdAt = value;
  }

  /**
   * Creates a new PaymentEvent RecordBuilder.
   * @return A new PaymentEvent RecordBuilder
   */
  public static com.emi.events.payment.PaymentEvent.Builder newBuilder() {
    return new com.emi.events.payment.PaymentEvent.Builder();
  }

  /**
   * Creates a new PaymentEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PaymentEvent RecordBuilder
   */
  public static com.emi.events.payment.PaymentEvent.Builder newBuilder(com.emi.events.payment.PaymentEvent.Builder other) {
    if (other == null) {
      return new com.emi.events.payment.PaymentEvent.Builder();
    } else {
      return new com.emi.events.payment.PaymentEvent.Builder(other);
    }
  }

  /**
   * Creates a new PaymentEvent RecordBuilder by copying an existing PaymentEvent instance.
   * @param other The existing instance to copy.
   * @return A new PaymentEvent RecordBuilder
   */
  public static com.emi.events.payment.PaymentEvent.Builder newBuilder(com.emi.events.payment.PaymentEvent other) {
    if (other == null) {
      return new com.emi.events.payment.PaymentEvent.Builder();
    } else {
      return new com.emi.events.payment.PaymentEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for PaymentEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PaymentEvent>
    implements org.apache.avro.data.RecordBuilder<PaymentEvent> {

    private java.lang.CharSequence eventId;
    private java.lang.CharSequence paymentId;
    private java.lang.CharSequence userKeycloakId;
    private java.lang.CharSequence currency;
    /** Amount in smallest currency unit */
    private long amount;
    private com.emi.events.payment.PaymentType paymentType;
    private com.emi.events.payment.PaymentStatus paymentStatus;
    private com.emi.events.payment.PaymentMethodType paymentMethod;
    private long createdAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.emi.events.payment.PaymentEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[1].schema(), other.paymentId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userKeycloakId)) {
        this.userKeycloakId = data().deepCopy(fields()[2].schema(), other.userKeycloakId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.currency)) {
        this.currency = data().deepCopy(fields()[3].schema(), other.currency);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.paymentType)) {
        this.paymentType = data().deepCopy(fields()[5].schema(), other.paymentType);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.paymentStatus)) {
        this.paymentStatus = data().deepCopy(fields()[6].schema(), other.paymentStatus);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.paymentMethod)) {
        this.paymentMethod = data().deepCopy(fields()[7].schema(), other.paymentMethod);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[8].schema(), other.createdAt);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing PaymentEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.emi.events.payment.PaymentEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.paymentId)) {
        this.paymentId = data().deepCopy(fields()[1].schema(), other.paymentId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userKeycloakId)) {
        this.userKeycloakId = data().deepCopy(fields()[2].schema(), other.userKeycloakId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.currency)) {
        this.currency = data().deepCopy(fields()[3].schema(), other.currency);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.paymentType)) {
        this.paymentType = data().deepCopy(fields()[5].schema(), other.paymentType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.paymentStatus)) {
        this.paymentStatus = data().deepCopy(fields()[6].schema(), other.paymentStatus);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.paymentMethod)) {
        this.paymentMethod = data().deepCopy(fields()[7].schema(), other.paymentMethod);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[8].schema(), other.createdAt);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPaymentId() {
      return paymentId;
    }


    /**
      * Sets the value of the 'paymentId' field.
      * @param value The value of 'paymentId'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setPaymentId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.paymentId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentId' field has been set.
      * @return True if the 'paymentId' field has been set, false otherwise.
      */
    public boolean hasPaymentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'paymentId' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearPaymentId() {
      paymentId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userKeycloakId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserKeycloakId() {
      return userKeycloakId;
    }


    /**
      * Sets the value of the 'userKeycloakId' field.
      * @param value The value of 'userKeycloakId'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setUserKeycloakId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userKeycloakId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userKeycloakId' field has been set.
      * @return True if the 'userKeycloakId' field has been set, false otherwise.
      */
    public boolean hasUserKeycloakId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userKeycloakId' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearUserKeycloakId() {
      userKeycloakId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.currency = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * Amount in smallest currency unit
      * @return The value.
      */
    public long getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * Amount in smallest currency unit
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setAmount(long value) {
      validate(fields()[4], value);
      this.amount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * Amount in smallest currency unit
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'amount' field.
      * Amount in smallest currency unit
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearAmount() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentType' field.
      * @return The value.
      */
    public com.emi.events.payment.PaymentType getPaymentType() {
      return paymentType;
    }


    /**
      * Sets the value of the 'paymentType' field.
      * @param value The value of 'paymentType'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setPaymentType(com.emi.events.payment.PaymentType value) {
      validate(fields()[5], value);
      this.paymentType = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentType' field has been set.
      * @return True if the 'paymentType' field has been set, false otherwise.
      */
    public boolean hasPaymentType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'paymentType' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearPaymentType() {
      paymentType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentStatus' field.
      * @return The value.
      */
    public com.emi.events.payment.PaymentStatus getPaymentStatus() {
      return paymentStatus;
    }


    /**
      * Sets the value of the 'paymentStatus' field.
      * @param value The value of 'paymentStatus'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setPaymentStatus(com.emi.events.payment.PaymentStatus value) {
      validate(fields()[6], value);
      this.paymentStatus = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentStatus' field has been set.
      * @return True if the 'paymentStatus' field has been set, false otherwise.
      */
    public boolean hasPaymentStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'paymentStatus' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearPaymentStatus() {
      paymentStatus = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'paymentMethod' field.
      * @return The value.
      */
    public com.emi.events.payment.PaymentMethodType getPaymentMethod() {
      return paymentMethod;
    }


    /**
      * Sets the value of the 'paymentMethod' field.
      * @param value The value of 'paymentMethod'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setPaymentMethod(com.emi.events.payment.PaymentMethodType value) {
      validate(fields()[7], value);
      this.paymentMethod = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'paymentMethod' field has been set.
      * @return True if the 'paymentMethod' field has been set, false otherwise.
      */
    public boolean hasPaymentMethod() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'paymentMethod' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearPaymentMethod() {
      paymentMethod = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public long getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder setCreatedAt(long value) {
      validate(fields()[8], value);
      this.createdAt = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.emi.events.payment.PaymentEvent.Builder clearCreatedAt() {
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PaymentEvent build() {
      try {
        PaymentEvent record = new PaymentEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.paymentId = fieldSetFlags()[1] ? this.paymentId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userKeycloakId = fieldSetFlags()[2] ? this.userKeycloakId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.currency = fieldSetFlags()[3] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.amount = fieldSetFlags()[4] ? this.amount : (java.lang.Long) defaultValue(fields()[4]);
        record.paymentType = fieldSetFlags()[5] ? this.paymentType : (com.emi.events.payment.PaymentType) defaultValue(fields()[5]);
        record.paymentStatus = fieldSetFlags()[6] ? this.paymentStatus : (com.emi.events.payment.PaymentStatus) defaultValue(fields()[6]);
        record.paymentMethod = fieldSetFlags()[7] ? this.paymentMethod : (com.emi.events.payment.PaymentMethodType) defaultValue(fields()[7]);
        record.createdAt = fieldSetFlags()[8] ? this.createdAt : (java.lang.Long) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PaymentEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<PaymentEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PaymentEvent>
    READER$ = (org.apache.avro.io.DatumReader<PaymentEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeString(this.paymentId);

    out.writeString(this.userKeycloakId);

    out.writeString(this.currency);

    out.writeLong(this.amount);

    out.writeEnum(this.paymentType.ordinal());

    out.writeEnum(this.paymentStatus.ordinal());

    out.writeEnum(this.paymentMethod.ordinal());

    out.writeLong(this.createdAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);

      this.userKeycloakId = in.readString(this.userKeycloakId instanceof Utf8 ? (Utf8)this.userKeycloakId : null);

      this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);

      this.amount = in.readLong();

      this.paymentType = com.emi.events.payment.PaymentType.values()[in.readEnum()];

      this.paymentStatus = com.emi.events.payment.PaymentStatus.values()[in.readEnum()];

      this.paymentMethod = com.emi.events.payment.PaymentMethodType.values()[in.readEnum()];

      this.createdAt = in.readLong();

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.paymentId = in.readString(this.paymentId instanceof Utf8 ? (Utf8)this.paymentId : null);
          break;

        case 2:
          this.userKeycloakId = in.readString(this.userKeycloakId instanceof Utf8 ? (Utf8)this.userKeycloakId : null);
          break;

        case 3:
          this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
          break;

        case 4:
          this.amount = in.readLong();
          break;

        case 5:
          this.paymentType = com.emi.events.payment.PaymentType.values()[in.readEnum()];
          break;

        case 6:
          this.paymentStatus = com.emi.events.payment.PaymentStatus.values()[in.readEnum()];
          break;

        case 7:
          this.paymentMethod = com.emi.events.payment.PaymentMethodType.values()[in.readEnum()];
          break;

        case 8:
          this.createdAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










