/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.payment;
@org.apache.avro.specific.AvroGenerated
public enum PaymentType implements org.apache.avro.generic.GenericEnumSymbol<PaymentType> {
  DEPOSIT, TRANSFER, WITHDRAW  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentType\",\"namespace\":\"com.emi.events.payment\",\"symbols\":[\"DEPOSIT\",\"TRANSFER\",\"WITHDRAW\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
