/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.payment;
@org.apache.avro.specific.AvroGenerated
public enum PaymentMethodType implements org.apache.avro.generic.GenericEnumSymbol<PaymentMethodType> {
  CARD, UPI, NET_BANKING, WALLET  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentMethodType\",\"namespace\":\"com.emi.events.payment\",\"symbols\":[\"CARD\",\"UPI\",\"NET_BANKING\",\"WALLET\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
