version: "3.8"

services:
  transaction-service:
    build:
      context: ../..
      dockerfile: transaction-service/Dockerfile
    container_name: payment-transaction-service
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/transactionservice_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/Payment-realm/protocol/openid-connect/certs
    ports:
      - "8084:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - Payment-net

networks:
  Payment-net:
    external: true
