version: "3.8"

services:
  notification-service:
    build:
      context: ../..
      dockerfile: notification-service/Dockerfile
    container_name: payment-notification-service
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/notificationservice_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/Payment-realm/protocol/openid-connect/certs
    ports:
      - "8089:8080"
    networks:
      - Payment-net

networks:
  Payment-net:
    external: true
