version: "3.8"

services:
  user-service:
    build:
      context: ../..
      dockerfile: user-service/Dockerfile
    container_name: payment-user-service
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/userservice_db
      MINIO_ENDPOINT: http://minio:9000
      MINIO_PRESIGN_ENDPOINT: http://host.docker.internal:9000 
      MINIO_PUBLIC_ENDPOINT: http://localhost:9000 
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: TRACE
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_CSRF: TRACE
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB_SERVLET: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: TRACE
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}     
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/Payment-realm/protocol/openid-connect/certs
    ports:
      - "8083:8080"
    networks:
      - Payment-net

networks:
  Payment-net:
    external: true
    name: Payment-net