/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.notification;
@org.apache.avro.specific.AvroGenerated
public enum EventType implements org.apache.avro.generic.GenericEnumSymbol<EventType> {
  TRANSACTION_SUCCESS, TRANSACTION_FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"com.emi.events.notification\",\"symbols\":[\"TRANSACTION_SUCCESS\",\"TRANSACTION_FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
