/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.notification;
@org.apache.avro.specific.AvroGenerated
public enum NotificationChannel implements org.apache.avro.generic.GenericEnumSymbol<NotificationChannel> {
  EMAIL, SMS, PUSH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotificationChannel\",\"namespace\":\"com.emi.events.notification\",\"symbols\":[\"EMAIL\",\"SMS\",\"PUSH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
