/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.notification;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class NotificationData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1758466452310785034L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotificationData\",\"namespace\":\"com.emi.events.notification\",\"fields\":[{\"name\":\"transactionId\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"long\"},{\"name\":\"currency\",\"type\":\"string\"},{\"name\":\"transactionType\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionType\",\"symbols\":[\"DEPOSIT\",\"WITHDRAW\",\"TRANSFER\"]}},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionStatus\",\"symbols\":[\"SUCCESS\",\"FAILED\"]}},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"fromAccountId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"toAccountId\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"message\",\"type\":[\"null\",\"string\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<NotificationData> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<NotificationData> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<NotificationData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<NotificationData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<NotificationData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this NotificationData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a NotificationData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a NotificationData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static NotificationData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence transactionId;
  private long amount;
  private java.lang.CharSequence currency;
  private com.emi.events.notification.TransactionType transactionType;
  private com.emi.events.notification.TransactionStatus status;
  private long timestamp;
  private java.lang.CharSequence fromAccountId;
  private java.lang.CharSequence toAccountId;
  private java.lang.CharSequence message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public NotificationData() {}

  /**
   * All-args constructor.
   * @param transactionId The new value for transactionId
   * @param amount The new value for amount
   * @param currency The new value for currency
   * @param transactionType The new value for transactionType
   * @param status The new value for status
   * @param timestamp The new value for timestamp
   * @param fromAccountId The new value for fromAccountId
   * @param toAccountId The new value for toAccountId
   * @param message The new value for message
   */
  public NotificationData(java.lang.CharSequence transactionId, java.lang.Long amount, java.lang.CharSequence currency, com.emi.events.notification.TransactionType transactionType, com.emi.events.notification.TransactionStatus status, java.lang.Long timestamp, java.lang.CharSequence fromAccountId, java.lang.CharSequence toAccountId, java.lang.CharSequence message) {
    this.transactionId = transactionId;
    this.amount = amount;
    this.currency = currency;
    this.transactionType = transactionType;
    this.status = status;
    this.timestamp = timestamp;
    this.fromAccountId = fromAccountId;
    this.toAccountId = toAccountId;
    this.message = message;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionId;
    case 1: return amount;
    case 2: return currency;
    case 3: return transactionType;
    case 4: return status;
    case 5: return timestamp;
    case 6: return fromAccountId;
    case 7: return toAccountId;
    case 8: return message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionId = (java.lang.CharSequence)value$; break;
    case 1: amount = (java.lang.Long)value$; break;
    case 2: currency = (java.lang.CharSequence)value$; break;
    case 3: transactionType = (com.emi.events.notification.TransactionType)value$; break;
    case 4: status = (com.emi.events.notification.TransactionStatus)value$; break;
    case 5: timestamp = (java.lang.Long)value$; break;
    case 6: fromAccountId = (java.lang.CharSequence)value$; break;
    case 7: toAccountId = (java.lang.CharSequence)value$; break;
    case 8: message = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public java.lang.CharSequence getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.CharSequence value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public long getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(long value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'transactionType' field.
   * @return The value of the 'transactionType' field.
   */
  public com.emi.events.notification.TransactionType getTransactionType() {
    return transactionType;
  }


  /**
   * Sets the value of the 'transactionType' field.
   * @param value the value to set.
   */
  public void setTransactionType(com.emi.events.notification.TransactionType value) {
    this.transactionType = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.emi.events.notification.TransactionStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.emi.events.notification.TransactionStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'fromAccountId' field.
   * @return The value of the 'fromAccountId' field.
   */
  public java.lang.CharSequence getFromAccountId() {
    return fromAccountId;
  }


  /**
   * Sets the value of the 'fromAccountId' field.
   * @param value the value to set.
   */
  public void setFromAccountId(java.lang.CharSequence value) {
    this.fromAccountId = value;
  }

  /**
   * Gets the value of the 'toAccountId' field.
   * @return The value of the 'toAccountId' field.
   */
  public java.lang.CharSequence getToAccountId() {
    return toAccountId;
  }


  /**
   * Sets the value of the 'toAccountId' field.
   * @param value the value to set.
   */
  public void setToAccountId(java.lang.CharSequence value) {
    this.toAccountId = value;
  }

  /**
   * Gets the value of the 'message' field.
   * @return The value of the 'message' field.
   */
  public java.lang.CharSequence getMessage() {
    return message;
  }


  /**
   * Sets the value of the 'message' field.
   * @param value the value to set.
   */
  public void setMessage(java.lang.CharSequence value) {
    this.message = value;
  }

  /**
   * Creates a new NotificationData RecordBuilder.
   * @return A new NotificationData RecordBuilder
   */
  public static com.emi.events.notification.NotificationData.Builder newBuilder() {
    return new com.emi.events.notification.NotificationData.Builder();
  }

  /**
   * Creates a new NotificationData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new NotificationData RecordBuilder
   */
  public static com.emi.events.notification.NotificationData.Builder newBuilder(com.emi.events.notification.NotificationData.Builder other) {
    if (other == null) {
      return new com.emi.events.notification.NotificationData.Builder();
    } else {
      return new com.emi.events.notification.NotificationData.Builder(other);
    }
  }

  /**
   * Creates a new NotificationData RecordBuilder by copying an existing NotificationData instance.
   * @param other The existing instance to copy.
   * @return A new NotificationData RecordBuilder
   */
  public static com.emi.events.notification.NotificationData.Builder newBuilder(com.emi.events.notification.NotificationData other) {
    if (other == null) {
      return new com.emi.events.notification.NotificationData.Builder();
    } else {
      return new com.emi.events.notification.NotificationData.Builder(other);
    }
  }

  /**
   * RecordBuilder for NotificationData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotificationData>
    implements org.apache.avro.data.RecordBuilder<NotificationData> {

    private java.lang.CharSequence transactionId;
    private long amount;
    private java.lang.CharSequence currency;
    private com.emi.events.notification.TransactionType transactionType;
    private com.emi.events.notification.TransactionStatus status;
    private long timestamp;
    private java.lang.CharSequence fromAccountId;
    private java.lang.CharSequence toAccountId;
    private java.lang.CharSequence message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.emi.events.notification.NotificationData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[3].schema(), other.transactionType);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.fromAccountId)) {
        this.fromAccountId = data().deepCopy(fields()[6].schema(), other.fromAccountId);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.toAccountId)) {
        this.toAccountId = data().deepCopy(fields()[7].schema(), other.toAccountId);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.message)) {
        this.message = data().deepCopy(fields()[8].schema(), other.message);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing NotificationData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.emi.events.notification.NotificationData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[0].schema(), other.transactionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.amount)) {
        this.amount = data().deepCopy(fields()[1].schema(), other.amount);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[3].schema(), other.transactionType);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[5].schema(), other.timestamp);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.fromAccountId)) {
        this.fromAccountId = data().deepCopy(fields()[6].schema(), other.fromAccountId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.toAccountId)) {
        this.toAccountId = data().deepCopy(fields()[7].schema(), other.toAccountId);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.message)) {
        this.message = data().deepCopy(fields()[8].schema(), other.message);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setTransactionId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.transactionId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearTransactionId() {
      transactionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public long getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setAmount(long value) {
      validate(fields()[1], value);
      this.amount = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearAmount() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.currency = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionType' field.
      * @return The value.
      */
    public com.emi.events.notification.TransactionType getTransactionType() {
      return transactionType;
    }


    /**
      * Sets the value of the 'transactionType' field.
      * @param value The value of 'transactionType'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setTransactionType(com.emi.events.notification.TransactionType value) {
      validate(fields()[3], value);
      this.transactionType = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionType' field has been set.
      * @return True if the 'transactionType' field has been set, false otherwise.
      */
    public boolean hasTransactionType() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'transactionType' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearTransactionType() {
      transactionType = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.emi.events.notification.TransactionStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setStatus(com.emi.events.notification.TransactionStatus value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setTimestamp(long value) {
      validate(fields()[5], value);
      this.timestamp = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearTimestamp() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'fromAccountId' field.
      * @return The value.
      */
    public java.lang.CharSequence getFromAccountId() {
      return fromAccountId;
    }


    /**
      * Sets the value of the 'fromAccountId' field.
      * @param value The value of 'fromAccountId'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setFromAccountId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.fromAccountId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'fromAccountId' field has been set.
      * @return True if the 'fromAccountId' field has been set, false otherwise.
      */
    public boolean hasFromAccountId() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'fromAccountId' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearFromAccountId() {
      fromAccountId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'toAccountId' field.
      * @return The value.
      */
    public java.lang.CharSequence getToAccountId() {
      return toAccountId;
    }


    /**
      * Sets the value of the 'toAccountId' field.
      * @param value The value of 'toAccountId'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setToAccountId(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.toAccountId = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'toAccountId' field has been set.
      * @return True if the 'toAccountId' field has been set, false otherwise.
      */
    public boolean hasToAccountId() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'toAccountId' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearToAccountId() {
      toAccountId = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'message' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage() {
      return message;
    }


    /**
      * Sets the value of the 'message' field.
      * @param value The value of 'message'.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder setMessage(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.message = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'message' field has been set.
      * @return True if the 'message' field has been set, false otherwise.
      */
    public boolean hasMessage() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'message' field.
      * @return This builder.
      */
    public com.emi.events.notification.NotificationData.Builder clearMessage() {
      message = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public NotificationData build() {
      try {
        NotificationData record = new NotificationData();
        record.transactionId = fieldSetFlags()[0] ? this.transactionId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.amount = fieldSetFlags()[1] ? this.amount : (java.lang.Long) defaultValue(fields()[1]);
        record.currency = fieldSetFlags()[2] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.transactionType = fieldSetFlags()[3] ? this.transactionType : (com.emi.events.notification.TransactionType) defaultValue(fields()[3]);
        record.status = fieldSetFlags()[4] ? this.status : (com.emi.events.notification.TransactionStatus) defaultValue(fields()[4]);
        record.timestamp = fieldSetFlags()[5] ? this.timestamp : (java.lang.Long) defaultValue(fields()[5]);
        record.fromAccountId = fieldSetFlags()[6] ? this.fromAccountId : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.toAccountId = fieldSetFlags()[7] ? this.toAccountId : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.message = fieldSetFlags()[8] ? this.message : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<NotificationData>
    WRITER$ = (org.apache.avro.io.DatumWriter<NotificationData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<NotificationData>
    READER$ = (org.apache.avro.io.DatumReader<NotificationData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.transactionId);

    out.writeLong(this.amount);

    out.writeString(this.currency);

    out.writeEnum(this.transactionType.ordinal());

    out.writeEnum(this.status.ordinal());

    out.writeLong(this.timestamp);

    if (this.fromAccountId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.fromAccountId);
    }

    if (this.toAccountId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.toAccountId);
    }

    if (this.message == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.message);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);

      this.amount = in.readLong();

      this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);

      this.transactionType = com.emi.events.notification.TransactionType.values()[in.readEnum()];

      this.status = com.emi.events.notification.TransactionStatus.values()[in.readEnum()];

      this.timestamp = in.readLong();

      if (in.readIndex() != 1) {
        in.readNull();
        this.fromAccountId = null;
      } else {
        this.fromAccountId = in.readString(this.fromAccountId instanceof Utf8 ? (Utf8)this.fromAccountId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.toAccountId = null;
      } else {
        this.toAccountId = in.readString(this.toAccountId instanceof Utf8 ? (Utf8)this.toAccountId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.message = null;
      } else {
        this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
      }

    } else {
      for (int i = 0; i < 9; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);
          break;

        case 1:
          this.amount = in.readLong();
          break;

        case 2:
          this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
          break;

        case 3:
          this.transactionType = com.emi.events.notification.TransactionType.values()[in.readEnum()];
          break;

        case 4:
          this.status = com.emi.events.notification.TransactionStatus.values()[in.readEnum()];
          break;

        case 5:
          this.timestamp = in.readLong();
          break;

        case 6:
          if (in.readIndex() != 1) {
            in.readNull();
            this.fromAccountId = null;
          } else {
            this.fromAccountId = in.readString(this.fromAccountId instanceof Utf8 ? (Utf8)this.fromAccountId : null);
          }
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.toAccountId = null;
          } else {
            this.toAccountId = in.readString(this.toAccountId instanceof Utf8 ? (Utf8)this.toAccountId : null);
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.message = null;
          } else {
            this.message = in.readString(this.message instanceof Utf8 ? (Utf8)this.message : null);
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










