/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.transactions;
@org.apache.avro.specific.AvroGenerated
public enum TransactionStatus implements org.apache.avro.generic.GenericEnumSymbol<TransactionStatus> {
  INITIATED, SUCCESS, FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TransactionStatus\",\"namespace\":\"com.emi.events.transactions\",\"symbols\":[\"INITIATED\",\"SUCCESS\",\"FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
