/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.emi.events.transactions;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5269767570753490096L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionEvent\",\"namespace\":\"com.emi.events.transactions\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"transactionId\",\"type\":\"string\"},{\"name\":\"currency\",\"type\":\"string\"},{\"name\":\"toAccountId\",\"type\":\"string\"},{\"name\":\"userKeycloakId\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"long\",\"doc\":\"Amount in smallest currency unit\"},{\"name\":\"transactionType\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionType\",\"symbols\":[\"DEPOSIT\",\"TRANSFER\",\"WITHDRAW\"]}},{\"name\":\"transactionStatus\",\"type\":{\"type\":\"enum\",\"name\":\"TransactionStatus\",\"symbols\":[\"INITIATED\",\"SUCCESS\",\"FAILED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TransactionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence eventId;
  private java.lang.CharSequence transactionId;
  private java.lang.CharSequence currency;
  private java.lang.CharSequence toAccountId;
  private java.lang.CharSequence userKeycloakId;
  /** Amount in smallest currency unit */
  private long amount;
  private com.emi.events.transactions.TransactionType transactionType;
  private com.emi.events.transactions.TransactionStatus transactionStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionEvent() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param transactionId The new value for transactionId
   * @param currency The new value for currency
   * @param toAccountId The new value for toAccountId
   * @param userKeycloakId The new value for userKeycloakId
   * @param amount Amount in smallest currency unit
   * @param transactionType The new value for transactionType
   * @param transactionStatus The new value for transactionStatus
   */
  public TransactionEvent(java.lang.CharSequence eventId, java.lang.CharSequence transactionId, java.lang.CharSequence currency, java.lang.CharSequence toAccountId, java.lang.CharSequence userKeycloakId, java.lang.Long amount, com.emi.events.transactions.TransactionType transactionType, com.emi.events.transactions.TransactionStatus transactionStatus) {
    this.eventId = eventId;
    this.transactionId = transactionId;
    this.currency = currency;
    this.toAccountId = toAccountId;
    this.userKeycloakId = userKeycloakId;
    this.amount = amount;
    this.transactionType = transactionType;
    this.transactionStatus = transactionStatus;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return eventId;
    case 1: return transactionId;
    case 2: return currency;
    case 3: return toAccountId;
    case 4: return userKeycloakId;
    case 5: return amount;
    case 6: return transactionType;
    case 7: return transactionStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: eventId = (java.lang.CharSequence)value$; break;
    case 1: transactionId = (java.lang.CharSequence)value$; break;
    case 2: currency = (java.lang.CharSequence)value$; break;
    case 3: toAccountId = (java.lang.CharSequence)value$; break;
    case 4: userKeycloakId = (java.lang.CharSequence)value$; break;
    case 5: amount = (java.lang.Long)value$; break;
    case 6: transactionType = (com.emi.events.transactions.TransactionType)value$; break;
    case 7: transactionStatus = (com.emi.events.transactions.TransactionStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }


  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public java.lang.CharSequence getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(java.lang.CharSequence value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'currency' field.
   * @return The value of the 'currency' field.
   */
  public java.lang.CharSequence getCurrency() {
    return currency;
  }


  /**
   * Sets the value of the 'currency' field.
   * @param value the value to set.
   */
  public void setCurrency(java.lang.CharSequence value) {
    this.currency = value;
  }

  /**
   * Gets the value of the 'toAccountId' field.
   * @return The value of the 'toAccountId' field.
   */
  public java.lang.CharSequence getToAccountId() {
    return toAccountId;
  }


  /**
   * Sets the value of the 'toAccountId' field.
   * @param value the value to set.
   */
  public void setToAccountId(java.lang.CharSequence value) {
    this.toAccountId = value;
  }

  /**
   * Gets the value of the 'userKeycloakId' field.
   * @return The value of the 'userKeycloakId' field.
   */
  public java.lang.CharSequence getUserKeycloakId() {
    return userKeycloakId;
  }


  /**
   * Sets the value of the 'userKeycloakId' field.
   * @param value the value to set.
   */
  public void setUserKeycloakId(java.lang.CharSequence value) {
    this.userKeycloakId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return Amount in smallest currency unit
   */
  public long getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * Amount in smallest currency unit
   * @param value the value to set.
   */
  public void setAmount(long value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'transactionType' field.
   * @return The value of the 'transactionType' field.
   */
  public com.emi.events.transactions.TransactionType getTransactionType() {
    return transactionType;
  }


  /**
   * Sets the value of the 'transactionType' field.
   * @param value the value to set.
   */
  public void setTransactionType(com.emi.events.transactions.TransactionType value) {
    this.transactionType = value;
  }

  /**
   * Gets the value of the 'transactionStatus' field.
   * @return The value of the 'transactionStatus' field.
   */
  public com.emi.events.transactions.TransactionStatus getTransactionStatus() {
    return transactionStatus;
  }


  /**
   * Sets the value of the 'transactionStatus' field.
   * @param value the value to set.
   */
  public void setTransactionStatus(com.emi.events.transactions.TransactionStatus value) {
    this.transactionStatus = value;
  }

  /**
   * Creates a new TransactionEvent RecordBuilder.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.emi.events.transactions.TransactionEvent.Builder newBuilder() {
    return new com.emi.events.transactions.TransactionEvent.Builder();
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.emi.events.transactions.TransactionEvent.Builder newBuilder(com.emi.events.transactions.TransactionEvent.Builder other) {
    if (other == null) {
      return new com.emi.events.transactions.TransactionEvent.Builder();
    } else {
      return new com.emi.events.transactions.TransactionEvent.Builder(other);
    }
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing TransactionEvent instance.
   * @param other The existing instance to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.emi.events.transactions.TransactionEvent.Builder newBuilder(com.emi.events.transactions.TransactionEvent other) {
    if (other == null) {
      return new com.emi.events.transactions.TransactionEvent.Builder();
    } else {
      return new com.emi.events.transactions.TransactionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionEvent>
    implements org.apache.avro.data.RecordBuilder<TransactionEvent> {

    private java.lang.CharSequence eventId;
    private java.lang.CharSequence transactionId;
    private java.lang.CharSequence currency;
    private java.lang.CharSequence toAccountId;
    private java.lang.CharSequence userKeycloakId;
    /** Amount in smallest currency unit */
    private long amount;
    private com.emi.events.transactions.TransactionType transactionType;
    private com.emi.events.transactions.TransactionStatus transactionStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.emi.events.transactions.TransactionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[1].schema(), other.transactionId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.toAccountId)) {
        this.toAccountId = data().deepCopy(fields()[3].schema(), other.toAccountId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.userKeycloakId)) {
        this.userKeycloakId = data().deepCopy(fields()[4].schema(), other.userKeycloakId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[6].schema(), other.transactionType);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.transactionStatus)) {
        this.transactionStatus = data().deepCopy(fields()[7].schema(), other.transactionStatus);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.emi.events.transactions.TransactionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[1].schema(), other.transactionId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.currency)) {
        this.currency = data().deepCopy(fields()[2].schema(), other.currency);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.toAccountId)) {
        this.toAccountId = data().deepCopy(fields()[3].schema(), other.toAccountId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.userKeycloakId)) {
        this.userKeycloakId = data().deepCopy(fields()[4].schema(), other.userKeycloakId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.amount)) {
        this.amount = data().deepCopy(fields()[5].schema(), other.amount);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[6].schema(), other.transactionType);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.transactionStatus)) {
        this.transactionStatus = data().deepCopy(fields()[7].schema(), other.transactionStatus);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'eventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }


    /**
      * Sets the value of the 'eventId' field.
      * @param value The value of 'eventId'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'eventId' field has been set.
      * @return True if the 'eventId' field has been set, false otherwise.
      */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'eventId' field.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setTransactionId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.transactionId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearTransactionId() {
      transactionId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'currency' field.
      * @return The value.
      */
    public java.lang.CharSequence getCurrency() {
      return currency;
    }


    /**
      * Sets the value of the 'currency' field.
      * @param value The value of 'currency'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setCurrency(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.currency = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'currency' field has been set.
      * @return True if the 'currency' field has been set, false otherwise.
      */
    public boolean hasCurrency() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'currency' field.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearCurrency() {
      currency = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'toAccountId' field.
      * @return The value.
      */
    public java.lang.CharSequence getToAccountId() {
      return toAccountId;
    }


    /**
      * Sets the value of the 'toAccountId' field.
      * @param value The value of 'toAccountId'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setToAccountId(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.toAccountId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'toAccountId' field has been set.
      * @return True if the 'toAccountId' field has been set, false otherwise.
      */
    public boolean hasToAccountId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'toAccountId' field.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearToAccountId() {
      toAccountId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'userKeycloakId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserKeycloakId() {
      return userKeycloakId;
    }


    /**
      * Sets the value of the 'userKeycloakId' field.
      * @param value The value of 'userKeycloakId'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setUserKeycloakId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.userKeycloakId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'userKeycloakId' field has been set.
      * @return True if the 'userKeycloakId' field has been set, false otherwise.
      */
    public boolean hasUserKeycloakId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'userKeycloakId' field.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearUserKeycloakId() {
      userKeycloakId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * Amount in smallest currency unit
      * @return The value.
      */
    public long getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * Amount in smallest currency unit
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setAmount(long value) {
      validate(fields()[5], value);
      this.amount = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * Amount in smallest currency unit
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'amount' field.
      * Amount in smallest currency unit
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearAmount() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionType' field.
      * @return The value.
      */
    public com.emi.events.transactions.TransactionType getTransactionType() {
      return transactionType;
    }


    /**
      * Sets the value of the 'transactionType' field.
      * @param value The value of 'transactionType'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setTransactionType(com.emi.events.transactions.TransactionType value) {
      validate(fields()[6], value);
      this.transactionType = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionType' field has been set.
      * @return True if the 'transactionType' field has been set, false otherwise.
      */
    public boolean hasTransactionType() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'transactionType' field.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearTransactionType() {
      transactionType = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionStatus' field.
      * @return The value.
      */
    public com.emi.events.transactions.TransactionStatus getTransactionStatus() {
      return transactionStatus;
    }


    /**
      * Sets the value of the 'transactionStatus' field.
      * @param value The value of 'transactionStatus'.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder setTransactionStatus(com.emi.events.transactions.TransactionStatus value) {
      validate(fields()[7], value);
      this.transactionStatus = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionStatus' field has been set.
      * @return True if the 'transactionStatus' field has been set, false otherwise.
      */
    public boolean hasTransactionStatus() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'transactionStatus' field.
      * @return This builder.
      */
    public com.emi.events.transactions.TransactionEvent.Builder clearTransactionStatus() {
      transactionStatus = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionEvent build() {
      try {
        TransactionEvent record = new TransactionEvent();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.transactionId = fieldSetFlags()[1] ? this.transactionId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.currency = fieldSetFlags()[2] ? this.currency : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.toAccountId = fieldSetFlags()[3] ? this.toAccountId : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.userKeycloakId = fieldSetFlags()[4] ? this.userKeycloakId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.amount = fieldSetFlags()[5] ? this.amount : (java.lang.Long) defaultValue(fields()[5]);
        record.transactionType = fieldSetFlags()[6] ? this.transactionType : (com.emi.events.transactions.TransactionType) defaultValue(fields()[6]);
        record.transactionStatus = fieldSetFlags()[7] ? this.transactionStatus : (com.emi.events.transactions.TransactionStatus) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionEvent>
    READER$ = (org.apache.avro.io.DatumReader<TransactionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.eventId);

    out.writeString(this.transactionId);

    out.writeString(this.currency);

    out.writeString(this.toAccountId);

    out.writeString(this.userKeycloakId);

    out.writeLong(this.amount);

    out.writeEnum(this.transactionType.ordinal());

    out.writeEnum(this.transactionStatus.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);

      this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);

      this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);

      this.toAccountId = in.readString(this.toAccountId instanceof Utf8 ? (Utf8)this.toAccountId : null);

      this.userKeycloakId = in.readString(this.userKeycloakId instanceof Utf8 ? (Utf8)this.userKeycloakId : null);

      this.amount = in.readLong();

      this.transactionType = com.emi.events.transactions.TransactionType.values()[in.readEnum()];

      this.transactionStatus = com.emi.events.transactions.TransactionStatus.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 8; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.eventId = in.readString(this.eventId instanceof Utf8 ? (Utf8)this.eventId : null);
          break;

        case 1:
          this.transactionId = in.readString(this.transactionId instanceof Utf8 ? (Utf8)this.transactionId : null);
          break;

        case 2:
          this.currency = in.readString(this.currency instanceof Utf8 ? (Utf8)this.currency : null);
          break;

        case 3:
          this.toAccountId = in.readString(this.toAccountId instanceof Utf8 ? (Utf8)this.toAccountId : null);
          break;

        case 4:
          this.userKeycloakId = in.readString(this.userKeycloakId instanceof Utf8 ? (Utf8)this.userKeycloakId : null);
          break;

        case 5:
          this.amount = in.readLong();
          break;

        case 6:
          this.transactionType = com.emi.events.transactions.TransactionType.values()[in.readEnum()];
          break;

        case 7:
          this.transactionStatus = com.emi.events.transactions.TransactionStatus.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










