package com.emi.transaction_service.requestDtos;

import java.math.BigDecimal;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

public record TransactionPayoutRequestDto(
		
		@NotBlank(message = "user ID is required")
	    @Size(max = 100, message = "recievers account Id must not exceed 100 characters (generated by stripe after taking bank credentials)")
	    @Schema(
	        description = "Unique Acc  identifier generated by the system",
	        example = "acct_1NabcdXYZ"
	    )
		String  recieversAccId,
        
        @NotNull(message = "Amount is required")
        @DecimalMin(value = "1.00", inclusive = true, message = "Amount must be greater than or equal to 1.00")
        @Schema(
            description = "Payment amount to be withdraw",
            example = "499.99",
            minimum = "1.00"
        )
        BigDecimal amount,
        
        @NotBlank
        @Pattern(regexp = "^[A-Z]{3}$")
        String currency

	
		) {

}
