spring.application.name=api-gateway
spring.security.oauth2.resourceserver.jwt.jwk-set-uri==http://keycloak:8080/realms/Payment-realm/protocol/openid-connect/certs

#Swagger -
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.urls[0].name=User-Service
springdoc.swagger-ui.urls[0].url=/aggregate/user-service/api-docs
springdoc.swagger-ui.urls[1].name=Payment-Service
springdoc.swagger-ui.urls[1].url=/aggregate/payment-service/api-docs
springdoc.swagger-ui.urls[2].name=Wallet-Service
springdoc.swagger-ui.urls[2].url=/aggregate/wallet-service/api-docs
springdoc.swagger-ui.urls[3].name=Transaction-Service
springdoc.swagger-ui.urls[3].url=/aggregate/transaction-service/api-docs




